### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by livxy** [dropout1337/hCaptcha-Images#1]
bro what even is this  dawg 
[![image](https://user-images.githubusercontent.com/67598470/194782434-817cca24-d7c3-4b5e-a277-07a5e27d27db.png)](https://github.com/dropout1337/hCaptcha-Images/blob/7f7947e5cbbc9155228be872861557085bcee4f8/images/penguin_surrounded_by_flowers/39b8151059b86b77c3fb15fd2a3b6c23.jpg)

😭

**Comment by livxy** [comment]
and what is it doing in willy wanka or some wizard of oz place bruh

**Comment by dropout1337** [comment]
🤣 now that penguin was added by Johnathan the 3rd to the hCaptcha images database, the image was taken back in 2002 inside a lab where they were testing the effects of ecstasy on penguins.

**Comment by livxy** [comment]
what 💀
